# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: topstream_dev
  pool: 5
  username: postgres
  password: aaw860
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: topstream_test
  pool: 5
  username: postgres
  password: aaw860
  host: 127.0.0.1

